name: Build and publish tags to ghcr.io
on:
  push:
    tags:
      - v*
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  WERF_STAGED_DOCKERFILE_VERSION: v2
  # WERF_BUILDAH_MODE: auto

jobs:
  build:
    name: build images for tag
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: werf/actions/install@v1.2

      - name: Login into ghcr.io
        shell: bash
        run: werf cr login -u ${{ github.actor }} -p ${{ github.token }} ghcr.io/${{ github.repository }}

      - name: Extract Docker metadata
        uses: docker/metadata-action@v5.6.1
        with:
          images: ghcr.io/${{ github.repository }}/${{ matrix.name }}

      - name: Build Image
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          source "$(werf ci-env github --as-file)"
          source <(jq -r '.labels | to_entries | to_entries[] | "export WERF_EXPORT_ADD_LABEL_\(.key)=\"\(.value.key)=\(.value.value)\""' <<< $DOCKER_METADATA_OUTPUT_JSON)

          werf build

      - name: Build and Push Image
        if: ${{ github.event_name != 'pull_request' }}
        run: |
          source "$(werf ci-env github --as-file)"
          source <(jq -r '.labels | to_entries | to_entries[] | "export WERF_EXPORT_ADD_LABEL_\(.key)=\"\(.value.key)=\(.value.value)\""' <<< $DOCKER_METADATA_OUTPUT_JSON)

          werf export --tag ghcr.io/${{ github.repository }}/%image%:${{ github.ref_name }}
